### ISSUE TITLE
Syntax error in install_firm.sh script

### ISSUE THREAD

**Issue by KasperFischer** [nadavbra/firm#1]
Dear @nadavbra 

I am installing FIRM to run a PWAS on my dataset. However, I am running into installation issues, which I hoped you could help me with. I am installin FIRM in order to run

```
firm_determine_extended_gene_effects_and_scores
```

I install FIRM with the installation script available on this github page. I type in the commands below:

```
wget https://raw.githubusercontent.com/nadavbra/firm/master/install_firm.sh
chmod a+x install_firm.sh
bash install_firm.sh

```
I get this syntax error:
```
install_firm.sh: line 14: syntax error near unexpected token `newline'
install_firm.sh: line 14: `set response = $<'
```

Do you know what is causing the error?

Best regards,

**Comment by nadavbra** [comment]
Please notice that this is a tcsh script, not bash. Try to run it with tcsh.
If you still get errors, I'd also suggest to try to run it line by line.

**Comment by KasperFischer** [comment]
Ok, then it makes sense to why I cannot run it. Thank you for your help!
