### ISSUE TITLE
failed load_classifier from FIRM softwar

### ISSUE THREAD

**Issue by LLing4368** [nadavbra/firm#2]
Dear Nadav:
        I encountered some problems when using FIRM software (https://github.com/nadavbra/firm). I cannot commit this command successfully. "firm_classifier = firm.load_classifier(geneffect_setup)". I have already finished setting up reference genome hg19. However, error message was shown as following. 
Traceback(most recent call last):
File"/home/l1/miniconda3/envs/PWAS/bin/firm_determine_extended_gene_effects_and_scores",line 4, in <module>
import_('pkg_resources').run_script('firm==1.3.0'，'firm_determine_extended_gene_effects_and_scores')
File"/home/11/miniconda3/envs/PWAS/lib/ovthon3.8/site-packaaes/okaresources/ init .ov". line 672. in run scri pt
self.require(requires)[0].run script(script name，ns)
File"/home/l1/miniconda3/envs/PWAS/lib/python3.8/site-packages/pkg_resources/_init_.py", line 1472, in run_scr ipt
exec(code,namespace,namespace)
File"/home/1l/miniconda3/envs/PWAS/lib/python3.8/site-packages/firm-1.3.0-py3.8-linux-x86_64.egg/EGG-INF0/script s/firm determine extended gene effects and scores"， line 90，in <module>
firm classifier = firm.load classifier(geneffect setup)
File"/home/L1/miniconda3/envs/PWAS/lib/bvthon3.8/site-backaaes/firm-1.3.0-pv3.8-linux-x86 64.eaa/firm/load class ifier.py",line 11, in load classifier
classifier.load(f)
File"/home/1l/miniconda3/envs/PWAS/lib/python3.8/site-packages/firm-1.3.0-py3.8-linux-x86_64.egg/firm/ml/classif ication.py", line 90, in load assert self.feature extractor.get feature names()= feature names 
AssertionError

Best wishes!

**Comment by nadavbra** [comment]
Hi @LLing4368,
I'm really sorry for the problem you are encountering. I admit that I'm not sure why you're getting this error. Ideally I'd try to re-install FIRM myself and see that I get it to work properly, but I'm incredibly overloaded right now (I need to submit a grant and a paper revision), so I'm not sure when I'll be able to get to looking at it.
One guess would be that it has to do with the version of Python or some of the packages you are using. This code was actually developed a while ago (last edited on Jan 21, 2021) and it could be that some assumptions have since broken. Maybe if you install the version of Python and all the other dependencies that were available at the time it might work for you.

**Comment by LLing4368** [comment]
Dear Nadav:
I really appreciate your reply. I will try your advice, maybe is the problem of python's dependencies. It's OK, I will to re-install it.&nbsp; I sincerely wish your paper can be accepted successfully.
Best wishes
Ling Lei










 

 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Thu, Jan 5, 2023 10:54 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [nadavbra/firm] failed load_classifier from FIRM softwar (Issue #2)

&nbsp;



 
Hi @LLing4368,
 I'm really sorry for the problem you are encountering. I admit that I'm not sure why you're getting this error. Ideally I'd try to re-install FIRM myself and see that I get it to work properly, but I'm incredibly overloaded right now (I need to submit a grant and a paper revision), so I'm not sure when I'll be able to get to looking at it.
 One guess would be that it has to do with the version of Python or some of the packages you are using. This code was actually developed a while ago (last edited on Jan 21, 2021) and it could be that some assumptions have since broken. Maybe if you install the version of Python and all the other dependencies that were available at the time it might work for you.

**Comment by LLing4368** [comment]
> Hi @LLing4368, I'm really sorry for the problem you are encountering. I admit that I'm not sure why you're getting this error. Ideally I'd try to re-install FIRM myself and see that I get it to work properly, but I'm incredibly overloaded right now (I need to submit a grant and a paper revision), so I'm not sure when I'll be able to get to looking at it. One guess would be that it has to do with the version of Python or some of the packages you are using. This code was actually developed a while ago (last edited on Jan 21, 2021) and it could be that some assumptions have since broken. Maybe if you install the version of Python and all the other dependencies that were available at the time it might work for you.
