### ISSUE TITLE
re-install firm software cannot sovle "load_classifier" problem

### ISSUE THREAD

**Issue by LLing4368** [nadavbra/firm#3]
Hi Nadav:
I tried to re-install firm software, but it still failed to solve the problem. Would it be convenient for you to tell me the version of all dependencies of your firm software? I would like to try to solve the problem based on  the same environment as you run.
Best wishes!

**Comment by RoeiZucker** [comment]
Hi!
I'm currently running firm and these are the current libraries installed on my environment:
Most of them are not necessary. Probably BGEN parser, geneffect, and hmmer are the most important.
Feel free to contact me on roei.zucker@mail.huji.ac.il for any help needed, some of these libraries are a bit tricky to install.

Package                       Version
----------------------------- ----------
absl-py                       0.15.0
aiohttp                       3.7.4
aiohttp-session               2.7.0
alabaster                     0.7.12
alembic                       1.8.1
appdirs                       1.4.4
argon2-cffi                   20.1.0
astunparse                    1.6.3
async-generator               1.10
async-timeout                 3.0.1
asyncinit                     0.2.4
attrs                         20.3.0
autopage                      0.5.1
Babel                         2.9.1
backcall                      0.2.0
bgen_parser                   1.0
biopython                     1.78
bleach                        3.3.0
bokeh                         1.4.0
boto3                         1.18.21
botocore                      1.21.21
cached-property               1.5.2
cachetools                    4.2.2
certifi                       2020.12.5
cffi                          1.14.5
chardet                       3.0.4
class-resolver                0.3.10
click                         7.1.2
click-default-group           1.2.2
cliff                         3.10.1
cloudpickle                   1.6.0
cmaes                         0.9.0
cmd2                          2.4.2
colorlog                      6.7.0
cycler                        0.10.0
cykhash                       1.0.2
Cython                        0.29.23
dask                          2021.6.2
dataclasses-json              0.5.7
decorator                     4.4.2
deepTools                     3.5.1
deeptoolsintervals            0.1.9
defusedxml                    0.7.1
Deprecated                    1.2.12
dill                          0.3.4
docdata                       0.0.3
docutils                      0.17.1
entrypoints                   0.3
et-xmlfile                    1.1.0
fasta-reader                  1.0.0
firm                          1.3.0
flatbuffers                   2.0
fsspec                        0.9.0
gast                          0.4.0
gcsfs                         0.8.0
geneffect                     1.2.4
gff-io                        0.0.2
google-api-core               1.31.1
google-auth                   1.34.0
google-auth-oauthlib          0.4.5
google-cloud-core             1.7.2
google-cloud-storage          1.25.0
google-pasta                  0.2.0
google-resumable-media        0.5.1
googleapis-common-protos      1.53.0
greenlet                      2.0.1
grpcio                        1.41.1
h5py                          3.5.0
hail                          0.2.74
hmmer                         0.1.0
humanize                      1.0.0
hurry.filesize                0.9
idna                          2.10
imagesize                     1.2.0
importlib-metadata            4.0.1
importlib-resources           5.1.2
iniconfig                     1.1.1
interval-tree                 0.3.4
ipykernel                     5.5.5
ipython                       7.24.1
ipython-genutils              0.2.0
ipywidgets                    7.6.3
isal                          0.10.0
janus                         0.6.1
jedi                          0.18.0
Jinja2                        3.0.1
jmespath                      0.10.0
joblib                        1.0.1
jsonschema                    3.2.0
jupyter                       1.0.0
jupyter-client                6.1.12
jupyter-console               6.4.0
jupyter-core                  4.7.1
jupyterlab-pygments           0.1.2
jupyterlab-widgets            1.0.0
keras                         2.7.0
Keras-Preprocessing           1.1.2
kiwisolver                    1.3.1
libclang                      12.0.0
locket                        0.2.1
lxml                          4.6.4
MACS3                         3.0.0a6
Mako                          1.2.4
Markdown                      3.3.4
MarkupSafe                    2.0.1
marshmallow                   3.19.0
marshmallow-enum              1.5.1
matplotlib                    3.4.1
matplotlib-inline             0.1.2
mistune                       0.8.4
mlxtend                       0.21.0
more-click                    0.1.2
more-itertools                8.7.0
multidict                     5.1.0
mypy-extensions               0.4.3
nbclient                      0.5.3
nbconvert                     6.0.7
nbformat                      5.1.3
nest-asyncio                  1.5.1
notebook                      6.4.0
numpy                         1.20.2
numpydoc                      1.1.0
nvidia-cublas-cu11            11.10.3.66
nvidia-cuda-nvrtc-cu11        11.7.99
nvidia-cuda-runtime-cu11      11.7.99
nvidia-cudnn-cu11             8.5.0.96
oauthlib                      3.1.1
openpyxl                      3.0.7
opt-einsum                    3.3.0
optuna                        3.0.4
packaging                     20.9
pandas                        1.1.4
pandas-plink                  2.2.8
pandocfilters                 1.4.3
parsimonious                  0.8.1
parso                         0.8.2
partd                         1.2.0
patsy                         0.5.1
pbr                           5.11.0
pexpect                       4.8.0
pickle5                       0.0.12
pickleshare                   0.7.5
Pillow                        8.2.0
pip                           22.2.1
pkg_resources                 0.0.0
plotly                        4.14.3
pluggy                        1.0.0.dev0
pooch                         1.3.0
prettytable                   3.5.0
prometheus-client             0.11.0
prompt-toolkit                3.0.18
protein-bert                  1.0.1
protobuf                      3.17.3
ptyprocess                    0.7.0
pwas                          1.0.2
py                            1.10.0
py2bit                        0.3.0
py4j                          0.10.9
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pyBigWig                      0.3.18
pycparser                     2.20
pyfaidx                       0.6.3.1
Pygments                      2.9.0
PyJWT                         2.1.0
pykeen                        1.8.1
pyparsing                     2.4.7
pyperclip                     1.8.2
pyrsistent                    0.17.3
pysam                         0.16.0.1
pyspark                       3.1.2
pystow                        0.4.7
pytest                        6.2.3
python-dateutil               2.8.1
python-json-logger            0.1.11
pytz                          2021.1
PyYAML                        5.4.1
pyzmq                         22.1.0
qtconsole                     5.1.0
QtPy                          1.9.0
requests                      2.25.1
requests-oauthlib             1.3.0
retrying                      1.3.3
rexmex                        0.1.2
rsa                           4.7.2
s3transfer                    0.5.0
scikit-learn                  1.0.2
scipy                         1.7.3
seaborn                       0.11.2
Send2Trash                    1.5.0
setuptools                    56.0.0
six                           1.15.0
sklearn                       0.0.post1
snowballstemmer               2.1.0
Sphinx                        4.0.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
SQLAlchemy                    1.4.45
statsmodels                   0.12.2
stevedore                     3.5.2
tabulate                      0.8.3
tensorboard                   2.7.0
tensorboard-data-server       0.6.1
tensorboard-plugin-wit        1.8.0
tensorflow-addons             0.14.0
tensorflow-estimator          2.7.0
tensorflow-io-gcs-filesystem  0.21.0
termcolor                     1.1.0
terminado                     0.10.0
testpath                      0.5.0
threadpoolctl                 2.1.0
toml                          0.10.2
toolz                         0.11.1
torch                         1.13.0
tornado                       6.1
tqdm                          4.42.1
traitlets                     5.0.5
typeguard                     2.13.0
typing-extensions             3.7.4.3
typing-inspect                0.8.0
ujson                         4.0.2
ukbb-parser                   1.0.2
urllib3                       1.26.4
wcwidth                       0.2.5
webencodings                  0.5.1
Werkzeug                      2.0.2
wheel                         0.36.2
widgetsnbextension            3.5.1
wrapt                         1.12.1
xarray                        0.18.2
xlrd                          2.0.1
xopen                         1.1.0
yarl                          1.6.3
zipp                          3.4.1
zstandard                     0.15.2
