### ISSUE TITLE
AssertError assert self.feature_extractor.get_feature_names() == feature_names

### ISSUE THREAD

**Issue by Captain-Pam** [nadavbra/firm#4]
Hi Nadav,

Thank you for your tool.  I have downloaded a new 'uniprot_human_reviewed.xml.gz' file from your new [link](https://rest.uniprot.org/uniprotkb/stream?compressed=true&download=true&format=xml&query=%28%28taxonomy_id%3A9606%29%29%20AND%20%28reviewed%3Atrue%29). I came across a problem when I carry out ''firm.load_classifier(geneffect_setup)". It throw an "AssertionError" from the code "assert self.feature_extractor.get_feature_names() == feature_names" about 90th line in classification.py. I found self.feature_extractor had 1100 features, but feature_names (from pickle.load (data/classifier.pkl)) had 1109 features. Is this caused by a different uniprot_human_reviewed.xml.gz file?  
The missing 9 features are ''context_global_track_metal-binding_count', 'context_5_track_metal-binding_count', 'context_left_10_track_metal-binding_count', 'context_right_10_track_metal-binding_count', 'context_left_track_metal-binding_count', 'context_right_track_metal-binding_count', 'track_metal-binding_distance', 'track_metal-binding_hit', 'track_metal-binding_miss''.

Additionally, "Failed creating 4 (PNP0x_C，SAMBD，Pyridox_oxidase，Toxin_1) of 2273 missing HMM profiles. " from code "geneffect_setup = geneffect.Setup('GRCh38)".

Any advice is worthwhile!
Thank you.

**Comment by nadavbra** [comment]
Hi @Captain-Pam 
My best guess is that the UniProt file you downloaded, for some reason, doesn't contain metal binding annotations. I'm not sure if it's because you downloaded the wrong file or UniProt has changed since this package was developed.
What are you hoping to use FIRM for? Is it for FABRIC or something else?

**Comment by Captain-Pam** [comment]
My purpose is PWAS. Do you share this file you are currently using? I want to test it. Also, can removing these nine features affect the results?

发自我的iPhone


------------------ Original ------------------
From: Nadav Brandes ***@***.***&gt;
Date: Tue,Mar 5,2024 0:56 AM
To: nadavbra/firm ***@***.***&gt;
Cc: Pam ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [nadavbra/firm] AssertError assertself.feature_extractor.get_feature_names() == feature_names (Issue #4)





 
Hi @Captain-Pam
 My best guess is that the UniProt file you downloaded, for some reason, doesn't contain metal binding annotations. I'm not sure if it's because you downloaded the wrong file or UniProt has changed since this package was developed.
 What are you hoping to use FIRM for? Is it for FABRIC or something else?

**Comment by nadavbra** [comment]
[uniprot_human_reviewed.xml.gz](https://drive.google.com/file/d/1rAAQuG5r71VYIvR8RS_mqq2GaYweNTSb/view?usp=sharing)
Does this file help?

**Comment by Captain-Pam** [comment]
> nadavbra

Thank you for sharing with me.
